local game = {}
game.version = "1.6"
game.name = "Ruined"
game.beta = "Early Developer Bèta"
game.buildName = "(DEV Build)"
game.chapter = 1
game.state = 1
-- 0 = main gameplay
-- 1 = title screen
-- 2 = cutscene,s and npc talks
-- 2.1 = talking
-- 2.2 = player walking show
-- 2.3 = camera movement
-- 2.4 = show and camera
-- 2.5 = show and talk
-- 2.6 = talk and camera
game.esc = false
game.controlType = 0
-- 0 = keyboard and mouse
-- 1 = controller
-- 2 = touchpad or phone
game.freeze = true
return game